#numpy 
fundamental package for scientific computing in python.
It provides a multidimensional array object , various derived objects , (such as masked arrays and matrices ) , and an assortment of routines for fast operation on arrays inclusing mathematical , logical , shape manipulation , sorting , selecting ,i/o , discrete fourier transfroms , basic linear algebra , basic statistical operations , random simulation and much more 

At the core of the NumPy package, it the ndarray object .
This encapsulates n-dimensional arrays of homogeneous data types 

===============================================
Numpy arrays have a fixed size at creating , unlike Python list (which can grow dynamically  ). Changing the size of an ndarray will create a new array and delete the original 

The elements in a numpy array are all required to be of the same data type , and thus will be the same size in memory 

# numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data , Typically such operations are executed more efficiently and with less code than is possible using python builts in sequences 

A growing plethora of scientific and mathematcial python based packages are using it 
It support python sequeneces input they convert such input to numpy arrays prior to processing and they often output numpy arrays
# god father of numpy 



In [4]:
# creating numpy arrays 
import numpy as np 
nums = np.array([1,2,3,4,5,6]) 
print(nums)
print(type(nums)) 


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
# 2d or 3d array 
d2 = np.array([[1,2,3,4,5] ,[5,6,7,8,9]]) # row and col must have same number of elements
print(d2) 

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [6]:
# dtype : data type 
flt = np.array([1,2,3,4] , dtype = float) 
print(flt) 

bl = np.array([1,2,3,4,5,0] ,dtype = bool) 
print(bl) 

[1. 2. 3. 4.]
[ True  True  True  True  True False]


In [7]:
# np.arange() : similar to range() of python 
rng = np.arange(1,11,2) # start , end , step 
print(rng) 

rng1 = np.arange(1,13).reshape(5,5) 
print(rng1) 

[1 3 5 7 9]


ValueError: cannot reshape array of size 12 into shape (5,5)

In [ ]:
# np.ones and np.zeros 

ones = np.ones((3,5)) ;
print(ones) 
# to initialize the array , used mostly in neural network 

zeros = np.zeros((3,4)) 
print(zeros) 

# np.random() 
rand = np.random.random((3,4)) # 0<=x <=1
print(rand) 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.53134368 0.42202038 0.08710005 0.95888808]
 [0.16372654 0.9486483  0.54855832 0.27468936]
 [0.07428538 0.57005159 0.47380242 0.11817179]]


In [ ]:
# np.linspace : linear spaced

ls = np.linspace(-10 ,10,10 , dtype = int ) # lower range , upper range , number of elements
print(ls) 
# equal distance par points generate karge 
# dtype = int 


[-10  -8  -6  -4  -2   1   3   5   7  10]


In [ ]:
# np.identity() : identity matrix



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
idn = np.identity(3) # 3x3        
print(idn )                     
print(idn.ndim)  # dimension   
print(idn.shape )# row and column  
print(idn.size) # total number of elements 
print(idn.itemsize) # 8  size of each items in bytes 

print(idn.dtype)# tells about the data types
      # float64 



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2
(3, 3)
9
8
float64


In [ ]:
# itemsize 
nums = np.array([1,2,3,4,5,6,7,8] ) 
print(nums)  

print(nums.itemsize) # number of elements  



[1 2 3 4 5 6 7 8]
8


In [ ]:
# changing data type of existing numpy array 
i = idn.astype(np.int32) # do not make changes in original array 
print(type(idn)) 
print(type(idn[0][0]) )
print(type(i[0][0]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.int32'>


In [ ]:
# array operations 
a1 = np.arange(12).reshape(3,4) 
a2 = np.arange(12,24).reshape(3,4) 

# scalar operation 
a3 = a1*5
print(a3) 
# all the arithmetic operators will work

# relational operator 
print(a2>5) # return the boolean array , True or False 
print(a1>6) 
print(a3>30) 

#  vector operation : b/w numpy array 
a4 = a1+a2 # explain it 
a5 = a1.__add__(a2) # yes it is working 

print(a4) 
print(a5) 

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False  True]
 [ True  True  True  True]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [ ]:
# min / max / sum / prod 
a1 = np.random.random((3,3)) 
a1 = np.round(a1*100) 
print(np.min(a1)) 
print(np.max(a1)) 
print(np.sum(a1)) 
print(np.prod(a1)) 
# 0-> col and row -> 1 
np.prod(a1 , axis =0)

2.0
78.0
289.0
224274645504.0


array([  576., 16614., 23436.])

In [ ]:
# mean / median / std / var 
print(np.mean(a1)) 
print(np.median(a1)) 
print(np.std(a1)) 
print(np.var(a1)) 

32.111111111111114
24.0
27.18432736561616
738.9876543209876


In [ ]:
# trigonometric functions
print(np.sin(-1)) 
print(np.cos(45)) 
print(np.tan(60)) 


-0.8414709848078965
0.5253219888177297
0.320040389379563


In [ ]:
# dot product of numpy array 3,4 4,3 - > 3,3 
a2 = np.arange(12).reshape(3,4) 
a3 = np.arange(12,24).reshape(4,3) 
a4 = np.dot(a1, a2) # dot product used in machine learning 
print(a4) # used in machine learnign 

[[ 396.  505.  614.  723.]
 [ 260.  306.  352.  398.]
 [ 744.  878. 1012. 1146.]]


In [ ]:
# round / floor / ceil 
a4 = np.random.random((2,3))*100
print(a4) 
# floor  : 6.9 -> 6
# ceil : 6.1 - > 7

print(np.ceil(a4)) 
print(np.floor(a4)) 

[[70.69466547 22.98683075 99.43140521]
 [73.69693002 93.84758256  2.1317943 ]]
[[ 71.  23. 100.]
 [ 74.  94.   3.]]
[[70. 22. 99.]
 [73. 93.  2.]]


In [9]:
# indexing and slicing 
a1 = np.arange(10) 
a2 = np.arange(12).reshape(3,4) 
a3 = np.arange(8).reshape(2,2,2) 
print(a2) 
print(a3) 


# last item of a1 
print(a1[-1]) 
print(a1[0]) 
print(a2[1][2] ) # 6
print(a2[1,0]) # fancy indexing [row , coloumn]

print(a3) # 3d tensor 
# fetch 5 
print(a3[1,0,1]) # [indexoftwod array , row , col]
print(a3[1][0][1]) # explain the working 

print(a3[0,0,0])
print(a3[1,1,0])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
9
0
6
4
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
5
0
6


In [ ]:
# slicing : helps to fetch multiple items 
print(a1) 
print(a1[2:5]) 
print(a1[-2:-5:-1]) # as same as python indexing 
print(a1[2:7:2])

# slicing on two d array 
print(a2[0,:]) 
print(a2[: ,2]) # all row and 2nd column 
print(a2[1: ,1:3]) 

# all corner element 
print(a2[::2,::3 ] )
# 1 3 9 11
print(a2[::2 , 1::2])
# 4 7 
print(a2[1,::3])


[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[8 7 6]
[2 4 6]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]


In [ ]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

# middle two d array 
print(a3[1]) 
# first and last 
print(a3[::2])

# print second row of first 2d array 
print(a3[0,1,:]) 
print(a3[1,:,1])
print(a3[2 , 1: ,1:])
print(a3[0::2 ,0,0::2])
print(30*"*")
# looping over 2d 
for i in a3 : 
    print(i) 

print(30*"*") 
for i in np.nditer(a3) : 
    print(i)

# 3d array ko pahale 1d array me convert kar rha hain uske baad one by one elements ko print kar rha hain 
#   

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]
******************************
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
******************************
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [44]:
# reshape 
# transpose : col <-> row interchange 

print(a3)
print(40*'*')
t = np.transpose(a3) # a3.T is alternative syntax 

print(t) # new array is formed 

# ravel : nd array ko 1d array me badlta hain 
a3_1 = a3.ravel()
print(a3_1)  

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
****************************************
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [47]:
# horizantal stacking 
# vertical stacking 

a4 = np.arange(12).reshape(3,4) 
a5 = np.arange(12,24).reshape(3,4) 
a6 = np.hstack((a4,a5)) # tuple as an argument 
print(a6)
a7 = np.vstack((a5 ,a4))
print(a7)  
# useful for data processing , coming from multiple sources 
# shape must be same

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
#spliting 
a7 = np.hsplit(a4, 2) # array name and number of equal part 
print(a7)
a8 = np.vsplit(a5 ,3) 
for i in a8 :
    for j in i : 
        print(j , end =" ") 
    print() 
print()

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[12 13 14 15] 
[16 17 18 19] 
[20 21 22 23] 

